repos:
        - repo: https://github.com/golangci/golangci-lint
          rev: v1.39.0
          hooks:
                  - id: golangci-lint
        - repo: https://github.com/dnephin/pre-commit-golang
          rev: v0.3.5
          hooks:
                  - id: go-lint
